EXECUTE sp_addextendedproperty N'MS_Description', N'机票订单表',N'user', N'dbo',N'table', N'IAT_FLIGHT_ORDER', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'SUPLIER_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'供应商ID(对应于SUPLIER_POLICY --供应商政策表的SUPLIER_ID 冗余字段)', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'SUPLIER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'采购商ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'PURCHASE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'原来的订单号', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORIGINAL_ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订座记录编号', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'PNR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单状态 （预定审核中 (10) 、审核退回(11)、待支付(12)、出票中(13)、已出票(14)、取消预定(15)）', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'更新订单状态时间(可以用作审核通过时间，或者退回时间等,具体每步操作时间可以查询订单日志)', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'UPDATE_STATUS_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'预定时间', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'审核回复', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_REPLAY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单备注', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否被锁定', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'LOCKED'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'LOCKED_OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者姓名', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'LOCKED_OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定时间', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'LOCKED_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单支付ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'ORDER_PAYMENT_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'运价', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'FREIGHT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'代理费率', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'AGENT_FEE_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励扣率', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'REWARD_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励金额', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'REWARD_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'税费', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'TAX'
 EXECUTE sp_addextendedproperty N'MS_Description', N'交易手续费', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'TRADING_FORMALITY_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'单张结算价', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'SETTLEMENT_PRICE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'其他费用', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'OTHER_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'其他费用说明(比如婴儿票 100)', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'OTHER_FEE_DESC'
 EXECUTE sp_addextendedproperty N'MS_Description', N'运价来源', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'FREIGHT_SOURCE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'供应商开票费', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'OPEN_TICKET_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单总价', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'TOTAL_PRICE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退改签规则', N'user', N'dbo', N'table', N'IAT_FLIGHT_ORDER', N'column', N'REFUND_RULE'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单支付信息表',N'user', N'dbo',N'table', N'IAT_ORDER_PAYMENT', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'ORDER_PAYMENT_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'票号', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'ORDER_TICKET_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付方式', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PAYMENT_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付金额', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PAYMENT_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付流水号', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'SERIAL_NUMBER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付账号', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PAYMENT_ACCOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'收款账号', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PROCEEDS_ACCOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'网银代码', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'NET_BANK_CODE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付时间', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PAYMENT_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'支付状态(0:支付失败，1：支付成功  2：未知)', N'user', N'dbo', N'table', N'IAT_ORDER_PAYMENT', N'column', N'PAYMENT_STATUS'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单留言表',N'user', N'dbo',N'table', N'IAT_ORDER_MESSAGE', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'ORDER_MESSAGE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'消息紧急级别(0:普通 1:较急  2:紧急  3:特急)', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'MESSAGE_LEVEL'
 EXECUTE sp_addextendedproperty N'MS_Description', N'消息标题', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'MESSAGE_TITLE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'消息内容', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'MESSAGE_CONTENT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'留言时间', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'LEAVE_WORD_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'操作员ID', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'OPERATOR_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'操作员名称', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方ID', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'PARTNER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方名称', N'user', N'dbo', N'table', N'IAT_ORDER_MESSAGE', N'column', N'PARTNER_NAME'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单保险费表',N'user', N'dbo',N'table', N'IAT_ORDER_INSURANCE', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_INSURANCE', N'column', N'ORDER_INSURANCE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_INSURANCE', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘机人ID', N'user', N'dbo', N'table', N'IAT_ORDER_INSURANCE', N'column', N'ORDER_PASSENGER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'保险单价', N'user', N'dbo', N'table', N'IAT_ORDER_INSURANCE', N'column', N'INS_UNIT_PRICE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'保险份数', N'user', N'dbo', N'table', N'IAT_ORDER_INSURANCE', N'column', N'INS_NUMBER'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单日志表',N'user', N'dbo',N'table', N'IAT_ORDER_LOG', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'ORDER_LOG_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'日志类型', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'LOG_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'标题', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'TITLE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'内容', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'CONTENT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'操作时间', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'OPERATE_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'操作者', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'操作者ID', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'OPERATOR_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'PARTNER_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方ID', N'user', N'dbo', N'table', N'IAT_ORDER_LOG', N'column', N'PARTNER_ID'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单航班信息表',N'user', N'dbo',N'table', N'IAT_FLIGHT_INFO', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'FLIGHT_INFO_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'起飞日期', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'TAKEOFF_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'起飞时间', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'TAKEOFF_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'出发机场三字码', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'DEPARTURE_AIRPORT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达机场三字码', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'ARRIVE_AIRPORT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航空公司', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'AIRLINE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航班号(最长4位)', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'FLIGHTS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达日期', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'ARRIVE_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达时间', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'ARRIVE_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'舱位(最长2位)', N'user', N'dbo', N'table', N'IAT_FLIGHT_INFO', N'column', N'BERTH'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单票号表',N'user', N'dbo',N'table', N'IAT_ORDER_TICKET', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID,', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'ORDER_TICKET_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘机人ID', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'ORDER_PASSENGERS_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'票号', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'TICKET_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'票号状态', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'TICKET_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'财务退款ID', N'user', N'dbo', N'table', N'IAT_ORDER_TICKET', N'column', N'FINANCIAL_REFUND_ID'
EXECUTE sp_addextendedproperty N'MS_Description', N'乘机人信息表',N'user', N'dbo',N'table', N'IAT_ORDER_PASSENGER', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'ORDER_PASSENGER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客英文姓名', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'PASSENGER_EN_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客类型(成人，儿童，婴儿 PASSENGER_TYPE表的主键ID）', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'PASSENGER_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客性别(男，女)', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'GENDER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件类型ID', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'DOCUMENT_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件号码', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'IDENTIFICATION_NUMBERS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件有效期', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'VALIDITY_PERIOD'
 EXECUTE sp_addextendedproperty N'MS_Description', N'出生日期', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'BIRTHDATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'国籍', N'user', N'dbo', N'table', N'IAT_ORDER_PASSENGER', N'column', N'NATIONALITY'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单联系人表',N'user', N'dbo',N'table', N'IAT_ORDER_CONTACT', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'ORDER_CONTACT_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人姓名', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'CONTACT_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人手机', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'MOBILE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人地址', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'ADDRESS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人电话', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'TELEPHONE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人EMAIL', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'EMAIL'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人QQ', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'QQ'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人MSN', N'user', N'dbo', N'table', N'IAT_ORDER_CONTACT', N'column', N'MSN'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单改签表',N'user', N'dbo',N'table', N'IAT_ORDER_ALTERATIONS', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ORDER_ALTERATIONS_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签票号', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ORDER_TICKET_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签后PNR', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'PNR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航班日期', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'TAKEOFF_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'起飞机场', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'TAKEOFF_AIRPORT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达机场', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ARRIVE_AIRPORT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航空公司', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'AIRLINE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航班号', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'FLIGHT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'起飞时间', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'TAKEOFF_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达时间', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ARRIVE_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达日期', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ARRIVE_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签信息', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ALTERATIONS_INFO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签补款', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'REPLENISH'
 EXECUTE sp_addextendedproperty N'MS_Description', N'回复', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'REPLAY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签备注', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ALTERATION_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签状态(改签审核中(20)、审核退回(21)、改签中(22)、待支付(23)、已改签(24)、已取消(25)(取消不必退款的，直接完成。需要退款的在退款表中新加一条记录，状态为待退款))', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'ALTERATION_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否被锁定', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'LOCKED'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者ID', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'LOCKED_OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者姓名', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'LOCKED_OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定时间', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'LOCKED_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'生成时间', N'user', N'dbo', N'table', N'IAT_ORDER_ALTERATIONS', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单退票表',N'user', N'dbo',N'table', N'IAT_ORDER_REFUND', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'ORDER_REFUND_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号(作为冗余字段)', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单票号ID', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'ORDER_TICKET_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退票标题', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REFUND_TITLE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退票原因说明', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REFUND_REASON'
 EXECUTE sp_addextendedproperty N'MS_Description', N'申请退票时间', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REFUND_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'实付金额（应该等于订单表中对应订单号的单张结算价）', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REAL_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'扣款金额', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'DEDUCT_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'实退金额', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REFUND_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退废票状态(退票审核中(30)、审核退回(31)、退票中(32)、已退票(33)(提交财务退款,需要退款的在退款表中新加一条记录，状态为待退款)、已取消(34) ,  废票审核中(40)、审核退回(41)、废票中(42)、取消废票(43)、废票完成(44))', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REFUND_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否被锁定', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'LOCKED'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者ID', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'LOCKED_OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者姓名', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'LOCKED_OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定时间', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'LOCKED_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否废票', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'IS_INVALIDATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'回复', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'REPLY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退回原因', N'user', N'dbo', N'table', N'IAT_ORDER_REFUND', N'column', N'RETURN_REASON'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单发票表',N'user', N'dbo',N'table', N'IAT_ORDER_INVOICE', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'ORDER_INVOICE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'金额', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'INVOICE_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'抬头', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'INVOICE_TITLE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发票派送方式(自取，到付)', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'INVOICE_SEND_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'自取地址', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'GET_INVOICE_ADDRESS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系人', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'CONTACT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'联系电话', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'CONTACT_PHONE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'派送地址', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'SEND_ADDRESS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否作废(默认为0，表示有效)', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'IS_INVALID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'快递号', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'EXPRESS_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发票状态(0:待开，1：已开)', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'INVOICE_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发票号', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'INVOICE_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开发票日期', N'user', N'dbo', N'table', N'IAT_ORDER_INVOICE', N'column', N'OPEN_INVOICE_DATE'
EXECUTE sp_addextendedproperty N'MS_Description', N'证件类型表',N'user', N'dbo',N'table', N'IAT_DOCUMENT_TYPE', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'DOCUMENT_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件类型编码', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'DOCUMENT_TYPE_CODE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件类型描述', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'DOCUMENT_TYPE_DESCRIPTION'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_DOCUMENT_TYPE', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'乘客类型表',N'user', N'dbo',N'table', N'IAT_PASSENGER_TYPE', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'PASSENGER_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客类型编码(ADT,CHD,)', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'PASSENGER_CODE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客类型描述（ 普通旅客、新移民、留学生、 劳务人员、  海员、外交官、儿童、婴儿)', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'DESCRIPTION'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_PASSENGER_TYPE', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'订单政策表(生成订单时匹配的政策，不允许修改)',N'user', N'dbo',N'table', N'IAT_ORDER_POLICY', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ORDER_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'SUPLIER_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'供应商ID', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'SUPPLIER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'源政策ID（复制政策时用）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ORIGINAL_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策类型（1：单程  2：往返  3：联程  4：缺口）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'POLICY_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策有效起始日期', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'POLICY_START_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策有效结束日期', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'POLICY_END_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'回程奖励政策沿用至', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'POLICY_CONTINUE_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票有效期开始日期，包含时分( 时间要不要分开)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'OPEN_TICKET_START_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票有效期结束日期，包含时分( 时间要不要分开)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'OPEN_TICKET_END_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'双休日开票开始时间（时分）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'WEEKEND_OPEN_TICKET_START_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'双休日开票结束时间（时分）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'WEEKEND_OPEN_TICKET_END_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'授权号1', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'OFFICE_NO1'
 EXECUTE sp_addextendedproperty N'MS_Description', N'授权号2', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'OFFICE_NO2'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航空公司二字码', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'AIRLINE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'基本代理费率', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'BASIC_AGENT_FEE_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励扣率', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'REWARD_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励金额', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'REWARD_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票费', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'OPEN_TICKET_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'舱位（以/分隔）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'BERTH'
 EXECUTE sp_addextendedproperty N'MS_Description', N'出发城市三字码', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'DEPARTURE_CITY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达城市三字码', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ARRIVE_CITY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'去程航班包含(多个航班以/ 分隔)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'GO_FLIGHT_INCLUDE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'返程航班包含(多个航班以/分隔)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'BACK_FLIGHT_INCLUDE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'机票类别（B2B,BSP,OET__境外电子票）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'TICKET_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否允许作废', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ALLOW_INVALID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'儿童票是否与成人票返点一致', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'CHILD_EQUAL_ADULT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'婴儿是否可开票', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'ALLOW_INFANT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'PNR限制（1：换编码出票 2:大编码出票(无需换编) 3：大编码出票(需换编) ）', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'PNR_LIMIT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'返点不适用(1:婴儿，2:儿童，3:整团，4:SOTO,5:代码共享)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'RETURN_RATE_LIMIT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策来源(确认政策来源是什么意思)', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'POLICY_SOURCE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'内部备注', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'INTERNAL_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'外部备注', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'EXTERNAL_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_ORDER_POLICY', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'供应商政策表',N'user', N'dbo',N'table', N'IAT_SUPLIER_POLICY', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'SUPLIER_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'供应商ID', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'SUPPLIER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'源政策ID（复制政策时用）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'ORIGINAL_POLICY_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策类型（1：单程  2：往返  3：联程  4：缺口）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'POLICY_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策有效起始日期', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'POLICY_START_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策有效结束日期', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'POLICY_END_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'回程奖励政策沿用至', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'POLICY_CONTINUE_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票有效期开始日期', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OPEN_TICKET_START_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'平时开票起始时间', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OPEN_TICKET_START_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票有效期结束日期', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OPEN_TICKET_END_DATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'平时开票结束时间', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OPEN_TICKET_END_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'双休日开票开始时间（时分）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'WEEKEND_OPEN_TICKET_START_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'双休日开票结束时间（时分）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'WEEKEND_OPEN_TICKET_END_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'授权号1', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OFFICE_NO1'
 EXECUTE sp_addextendedproperty N'MS_Description', N'授权号2', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OFFICE_NO2'
 EXECUTE sp_addextendedproperty N'MS_Description', N'航空公司二字码', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'AIRLINE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'基本代理费率', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'BASIC_AGENT_FEE_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励扣率', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'REWARD_RATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'奖励金额', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'REWARD_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票费', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'OPEN_TICKET_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'舱位（以/分隔,*代表所有舱位）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'BERTH'
 EXECUTE sp_addextendedproperty N'MS_Description', N'出发城市三字码', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'DEPARTURE_CITY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'到达城市三字码', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'ARRIVE_CITY'
 EXECUTE sp_addextendedproperty N'MS_Description', N'去程航班包含(多个航班以/ 分隔，不能和排除有冲突)', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'GO_FLIGHT_INCLUDE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'返程航班包含(多个航班以/分隔，不能和排除有冲突)', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'BACK_FLIGHT_INCLUDE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'机票类别（B2B,BSP,OET__境外电子票）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'TICKET_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否允许作废', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'ALLOW_INVALID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'儿童票是否与成人票返点一致', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'CHILD_EQUAL_ADULT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'婴儿是否可开票(0:不可开 1：可开)', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'ALLOW_INFANT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'PNR限制（1：换编码出票 2:大编码出票(无需换编) 3：大编码出票(需换编) ）', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'PNR_LIMIT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'返点不适用 编码方式为12345(1:婴儿，2:儿童，3:整团，4:SOTO,5:代码共享)', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'RETURN_RATE_LIMIT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策来源(确认政策来源是什么意思)', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'POLICY_SOURCE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'内部备注', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'INTERNAL_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'外部备注', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'EXTERNAL_REMARK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'CREATE_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'政策是否挂起', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'SUSPENDED'
 EXECUTE sp_addextendedproperty N'MS_Description', N'设置挂起状态的操作者ID', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'SET_SUSPENDED_OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'设置挂起的时间', N'user', N'dbo', N'table', N'IAT_SUPLIER_POLICY', N'column', N'SUSPENDED_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'平台配置表',N'user', N'dbo',N'table', N'IAT_PLATFORM_CONFIG', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'PLATFORM_CONFIG_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'PARTNER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'工作日开票开始时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'WORKDAY_OPEN_TICKET_START_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'工作日开票结束时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'WORKDAY_OPEN_TICKET_END_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'周末开票开始时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'WEEKEND_OPEN_TICKET_START_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'周末开票结束时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'WEEKEND_OPEN_TICKET_END_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'公休是否开票（0：开票，1：不开票）', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'REST_NO_TICKET'
 EXECUTE sp_addextendedproperty N'MS_Description', N'废票时间(比如 18:00以前)', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'INVALID_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'开票费', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'OPEN_TICKET_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'废票费', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'INVALID_TICKET_FEE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_CONFIG', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'平台快递表',N'user', N'dbo',N'table', N'IAT_PLATFORM_EXPRESS', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'PLATFORM_EXPRESS_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'快递名称', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'EXPRESS_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'PARTNER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'CREATER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建人ID', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'CREATER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'IAT_PLATFORM_EXPRESS', N'column', N'CREATE_TIME'
EXECUTE sp_addextendedproperty N'MS_Description', N'常旅客',N'user', N'dbo',N'table', N'IAT_FREQUENT_FLYER', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'FREQUENT_FLYER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'合作方ID', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'PARTNER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'英文姓名', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'ENGLIGH_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客类型ID', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'PASSENGER_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'乘客性别(男，女)', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'GENDER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件类型ID', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'DOCUMENT_TYPE_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件号码', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'IDENTIFICATION_NUMBERS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'证件有效期', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'VALIDITY_PERIOD'
 EXECUTE sp_addextendedproperty N'MS_Description', N'出生日期', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'BIRTHDATE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'国籍', N'user', N'dbo', N'table', N'IAT_FREQUENT_FLYER', N'column', N'NATIONALITY'
EXECUTE sp_addextendedproperty N'MS_Description', N'发票信息管理表',N'user', N'dbo',N'table', N'IAT_INVOICE_INFO', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'INVOICE_INFO_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发票册编号', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'INVOICE_BOOK_NUMBER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'每册张数', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'PAGES_PER_BOOK'
 EXECUTE sp_addextendedproperty N'MS_Description', N'初始票号', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'START_NUMBER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'结束票号', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'END_NUMBER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'入库时间', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'ADD_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发放时间', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'GRANT_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发放出处', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'GRANT_SOURCE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发放状态 （0：未发放 1：已发放）', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'添加人', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'添加人ID', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'OPERATOR_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发放人ID', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'GRANT_OPERATOR_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'发放人姓名', N'user', N'dbo', N'table', N'IAT_INVOICE_INFO', N'column', N'GRANT_OPERATOR_NAME'
EXECUTE sp_addextendedproperty N'MS_Description', N'财务退款表',N'user', N'dbo',N'table', N'IAT_FINANCIAL_REFUND', NULL, NULL
 EXECUTE sp_addextendedproperty N'MS_Description', N'主键ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'FINANCIAL_REFUND_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'供应商ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'SUPPLIER_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'订单号', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'ORDER_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'票号', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'ORDER_TICKET_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款金额', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_AMOUNT'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款状态  退款审核中(50)、审核退回(51)、退款中(52)、退款完成(53)', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_STATUS'
 EXECUTE sp_addextendedproperty N'MS_Description', N'提交退款人ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REQUEST_REFUND_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'提交退款时间', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REQUEST_REFUND_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'客户支付流水号', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'PAYMENT_SERIAL_NUMBER'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款批次号', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_BATCH_NO'
 EXECUTE sp_addextendedproperty N'MS_Description', N'是否被锁定', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'LOCKED'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'LOCKED_OPERATOR'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定者姓名', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'LOCKED_OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'锁定时间', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'LOCKED_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款类型（1：退票，2：废票 ，3：改签）', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_TYPE'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退票ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'ORDER_REFUND_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'改签ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'ORDER_ALTERATIONS_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'废票ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'INVALID_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款人ID', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_OPERATOR_ID'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款人姓名', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_OPERATOR_NAME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'退款时间', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'REFUND_TIME'
 EXECUTE sp_addextendedproperty N'MS_Description', N'生成时间', N'user', N'dbo', N'table', N'IAT_FINANCIAL_REFUND', N'column', N'CREATE_TIME'
