{{args['callback'][0]}}(['不限'
,'Z-中国国航-CA'
,'N-南方航空-CZ'
,'D-东方航空-MU'
,'A-奥凯航空公司-BK'
,'B-北京首都航空有限公司-JD'
,'C-成都航空有限公司-EU'
,'D-大新华航空公司-CN'
,'H-河北航空公司-NS'
,'H-海南航空公司-HU'
,'H-河南航空有限公司-VD'
,'H-华夏航空公司-G5'
,'J-吉祥航空公司-HO'
,'K-昆明航空有限公司-KY'
,'S-四川航空公司-3U'
,'S-山东航空公司-SC'
,'S-深圳航空公司-ZH'
,'S-上海航空公司-FM'
,'T-天津航空有限责任公司-GS'
,'X-西部航空公司-PN'
,'X-幸福航空有限责任公司-JR'
,'X-厦门航空有限公司-MF'
,'X-祥鹏航空公司-8L'
,'Z-中国联合航空公司-KN'])

$$.module.address.source.airline="@CA|中国国际航空|CA|Air China@MU|东方航空|MU|China Eastern Airlines@CZ|南方航空|CZ|China Southern Airlines@FM|上海航空|FM|Shanghai Airlines@SQ|新加坡航空|SQ|Singapore Airlines@CX|国泰航空|CX|Cathay Pacific Airways@UA|美联航|UA|United Airlines@HX|香港航空|HX|Hong Kong Airlines@QR|卡塔尔航空|QR|Qatar Airways@MH|马来西亚航空|MH|Malaysia Airlines@BA|英国航空|BA|British Airways@CI|中华航空|CI|China Airlines@AA|美国航空|AA|American Airlines@AF|法国航空|AF|Air France@KA|港龙航空|KA|Dragonair@LH|汉莎航空|LH|Lufthansa German Airlines@EK|阿联酋航空|EK|Emirates@NX|澳门航空|NX|Air Macau@AC|加拿大航空|AC|Air Canada@DL|达美航空|DL|Delta Air Lines@OZ|韩亚航空|OZ|Asiana Airlines@BR|长荣航空|BR|EVA Airways@QF|澳洲航空|QF|Qantas Airways@HU|海南航空|HU|Hainan Airlines@GE|复兴航空|GE|TransAsia Airways@KL|荷兰航空|KL|KLM Royal Dutch Airlines@TG|泰国航空|TG|Thai Airways International@KE|大韩航空|KE|Korean Air@JL|日本航空|JL|Japan Airlines@VS|维珍航空|VS|Virgin Atlantic@AY|芬兰航空|AY|Finnair@NH|全日空|NH|All Nippon Airways@HO|吉祥航空|HO|Juneyao Airlines@UO|香港快运航空|UO|Hong Kong Express Airways@SK|北欧航空|SK|SAS-Scandinavian Airlines@TK|土耳其航空|TK|Turkish Airlines@EY|阿提哈德航空|EY|ETIHAD AIRWAYS@SU|俄罗斯航空|SU|Aeroflot-Russian International Airlines@LX|瑞士航空|LX|Swiss International Air Lines@NZ|新西兰航空|NZ|Air New Zealand@AM|墨西哥航空|AM|Aeromexico Aerovias De Mexico@SA|南非航空|SA|South African Airways@VN|越南航空|VN|Vietnam Airlines@BT|汶莱皇家航空|BI|Royal Brunei Airlines@PR|菲律宾航空|PR|Philippine Airlines@AI|印度航空|AI|Air India@GA|印尼鹰航|GA|Garuda Indonesia@KQ|肯尼亚航空|KQ|Kenya Airways@ET|埃塞俄比亚航空|ET|Ethiopian Airlines@MF|厦门航空|MF|Xiamen Airlines@ZH|深圳航空|ZH|Shenzhen Airlines@UL|斯里兰卡航空|UL|SriLankan Airlines@AE|华信航空|AE|MandArin Airlines@9W|印度捷特航空|9W|Jet Airways India@KC|阿斯塔纳航空|KC|Air Astana@SC|山东航空|SC|Shandong Airlines@AZ|意大利航空|AZ|Alitalia@3U|四川航空|3U|Sichuan Airlines@S7|西伯利亚航空|S7|Siberia Airlines@LO|波兰航空|LO|Lot-Polish Airlines@MD|马达加斯加航空|MD|Societe Nationale Malgache de Transports@MI|胜安航空|MI|SilkAir@OM|蒙古航空|OM|Miat Mongolian Airlines@HY|乌兹别克斯坦航空|HY|Uzbekistan Airways@AH|阿尔及利亚航空|AH|AIR ALGERIE@B7|立荣航空|B7|UNI AIRWAYS@PG|曼谷航空|PG|Bangkok Airways@XF|海参崴航空|XF|Vladivostok Air@GS|天津航空|GS|TIANJIN AIRLINES@VV|乌克兰航空|VV|Aerosvit Airlines@UN|洲际航空|UN|Transaero Airlines@MK|毛里求斯航空|MK|AIR MAURITIUS@SN|布鲁塞尔航空|SN|SAB Sabena@MS|埃及航空|MS|Egypt Air@OS|奥地利航空|OS|Austrian Airlines@LY|以色列航空|LY|EL AL Israel Airlines@U6|乌拉尔航空|U6|URAL AIRLINES@SV|沙特航空|SV|SAUDIA@";
