var hot_list = [{ "NationShort": "AAA", "NationEnName": "China", "NationName": "中国" },
{ "NationShort": "AAA", "NationEnName": "United States", "NationName": "美国" },
{ "NationShort": "AAA", "NationEnName": "United Kingdom", "NationName": "英国" },
{ "NationShort": "AAA", "NationEnName": "Japan", "NationName": "日本" },
{ "NationShort": "AAA", "NationEnName": "Canada", "NationName": "加拿大" },
{ "NationShort": "AAA", "NationEnName": "France", "NationName": "法国" },
{ "NationShort": "AAA", "NationEnName": "Korea", "NationName": "韩国" },
{ "NationShort": "AAA", "NationEnName": "Germany", "NationName": "德国" }
]
var jsonNations = [{ "NationShort": "AF", "NationEnName": "Afghanistan", "NationName": "阿富汗" },
{ "NationShort": "AX ", "NationEnName": "Aland Islands", "NationName": "奥兰群岛" },
{ "NationShort": "AL", "NationEnName": "Albania", "NationName": "阿尔巴尼亚" },
{ "NationShort": "DZ", "NationEnName": "Algeria", "NationName": "阿尔及利亚" },
{ "NationShort": "AS", "NationEnName": "American Samoa", "NationName": "美属萨摩亚" },
{ "NationShort": "AD", "NationEnName": "Andorra", "NationName": "安道尔" },
{ "NationShort": "AO", "NationEnName": "Angola", "NationName": "安哥拉" },
{ "NationShort": "AI", "NationEnName": "Anguilla", "NationName": "安圭拉" },
{ "NationShort": "AG", "NationEnName": "Antigua and Barbuda", "NationName": "安提瓜和巴布达" },
{ "NationShort": "AR", "NationEnName": "Argentina", "NationName": "阿根廷" },
{ "NationShort": "AM", "NationEnName": "Armenia", "NationName": "亚美尼亚" },
{ "NationShort": "AW", "NationEnName": "Aruba", "NationName": "阿鲁巴" },
{ "NationShort": "AU", "NationEnName": "Australia", "NationName": "澳大利亚" },
{ "NationShort": "AT", "NationEnName": "Austria", "NationName": "奥地利" },
{ "NationShort": "AZ", "NationEnName": "Azerbaijan", "NationName": "阿塞拜疆" },
{ "NationShort": "BD", "NationEnName": "Bangladesh", "NationName": "孟加拉" },
{ "NationShort": "BH", "NationEnName": "Bahrain", "NationName": "巴林" },
{ "NationShort": "BS", "NationEnName": "Bahamas", "NationName": "巴哈马" },
{ "NationShort": "BB", "NationEnName": "Barbados", "NationName": "巴巴多斯" },
{ "NationShort": "BE", "NationEnName": "Belgium", "NationName": "比利时" },
{ "NationShort": "BZ", "NationEnName": "Belize", "NationName": "伯利兹" },
{ "NationShort": "BJ", "NationEnName": "Benin", "NationName": "贝宁" },
{ "NationShort": "BM", "NationEnName": "Bermuda", "NationName": "百慕大" },
{ "NationShort": "BT", "NationEnName": "Bhutan", "NationName": "不丹" },
{ "NationShort": "BO", "NationEnName": "Bolivia", "NationName": "玻利维亚" },
{ "NationShort": "BA", "NationEnName": "Bosnia and Herzegovina", "NationName": "波斯尼亚和黑塞哥维那" },
{ "NationShort": "BW", "NationEnName": "Botswana", "NationName": "博茨瓦纳" },
{ "NationShort": "BV", "NationEnName": "Bouvet Island", "NationName": "布维岛" },
{ "NationShort": "BR", "NationEnName": "Brazil", "NationName": "巴西" },
{ "NationShort": "BN", "NationEnName": "Brunei", "NationName": "文莱" },
{ "NationShort": "BG", "NationEnName": "Bulgaria", "NationName": "保加利亚" },
{ "NationShort": "BF", "NationEnName": "Burkina Faso", "NationName": "布基纳法索" },
{ "NationShort": "BI", "NationEnName": "Burundi", "NationName": "布隆迪" },
{ "NationShort": "KH", "NationEnName": "Cambodia", "NationName": "柬埔寨" },
{ "NationShort": "CM", "NationEnName": "Cameroon", "NationName": "喀麦隆" },
{ "NationShort": "BV", "NationEnName": "Bouvet Island", "NationName": "布维岛" },
{ "NationShort": "CA", "NationEnName": "Canada", "NationName": "加拿大" },
{ "NationShort": "CV", "NationEnName": "Cape Verde", "NationName": "佛得角" },
{ "NationShort": "CF", "NationEnName": "Central African Republic", "NationName": "中非" },
{ "NationShort": "TD", "NationEnName": "Chad", "NationName": "乍得" },
{ "NationShort": "CL", "NationEnName": "Chile", "NationName": "智利" },
{ "NationShort": "CX", "NationEnName": "Christmas Islands", "NationName": "圣诞岛" },
{ "NationShort": "CC", "NationEnName": "Cocos (keeling) Islands", "NationName": "科科斯（基林）群岛" },
{ "NationShort": "CO", "NationEnName": "Colombia", "NationName": "哥伦比亚" },
{ "NationShort": "KM", "NationEnName": "Comoros", "NationName": "科摩罗" },
{ "NationShort": "CD", "NationEnName": "Congo (Congo-Kinshasa)", "NationName": "刚果（金）" },
{ "NationShort": "CG", "NationEnName": "Congo", "NationName": "刚果" },
{ "NationShort": "CK", "NationEnName": "Cook Islands", "NationName": "库克群岛" },
{ "NationShort": "CR", "NationEnName": "Costa Rica", "NationName": "哥斯达黎加" },
{ "NationShort": "CI", "NationEnName": "Cote D'Ivoire", "NationName": "科特迪瓦" },
{ "NationShort": "CN", "NationEnName": "China", "NationName": "中国" },
{ "NationShort": "HR", "NationEnName": "Croatia", "NationName": "克罗地亚" },
{ "NationShort": "CU", "NationEnName": "Cuba", "NationName": "古巴" },
{ "NationShort": "CZ", "NationEnName": "Czech", "NationName": "捷克" },
{ "NationShort": "CY", "NationEnName": "Cyprus", "NationName": "塞浦路斯" },
{ "NationShort": "DK", "NationEnName": "Denmark", "NationName": "丹麦" },
{ "NationShort": "DJ", "NationEnName": "Djibouti", "NationName": "吉布提" },
{ "NationShort": "DM", "NationEnName": "Dominica", "NationName": "多米尼加" },
{ "NationShort": "CY", "NationEnName": "East Timor", "NationName": "东帝汶" },
{ "NationShort": "CY", "NationEnName": "Ecuador", "NationName": "厄瓜多尔" },
{ "NationShort": "CY", "NationEnName": "Egypt", "NationName": "埃及" },
{ "NationShort": "GQ", "NationEnName": "Equatorial Guinea", "NationName": "赤道几内亚" },
{ "NationShort": "ER", "NationEnName": "Eritrea", "NationName": "厄立特里亚" },
{ "NationShort": "EE", "NationEnName": "Estonia", "NationName": "爱沙尼亚" },
{ "NationShort": "ET", "NationEnName": "Ethiopia", "NationName": "埃塞俄比亚" },
{ "NationShort": "FO", "NationEnName": "Faroe Islands", "NationName": "法罗群岛" },
{ "NationShort": "FJ", "NationEnName": "Fiji", "NationName": "斐济" },
{ "NationShort": "FI", "NationEnName": "Finland", "NationName": "芬兰" },
{ "NationShort": "FR", "NationEnName": "France", "NationName": "法国" },
{ "NationShort": "FX", "NationEnName": "Franch Metropolitan", "NationName": "法国大都会" },
{ "NationShort": "GF", "NationEnName": "Franch Guiana", "NationName": "法属圭亚那" },
{ "NationShort": "PF", "NationEnName": "French Polynesia", "NationName": "法属波利尼西亚" },
{ "NationShort": "GA", "NationEnName": "Gabon", "NationName": "加蓬" },
{ "NationShort": "GM", "NationEnName": "Gambia", "NationName": "冈比亚" },
{ "NationShort": "GE", "NationEnName": "Georgia", "NationName": "格鲁吉亚" },
{ "NationShort": "DE", "NationEnName": "Germany", "NationName": "德国" },
{ "NationShort": "GI", "NationEnName": "Gibraltar", "NationName": "直布罗陀" },
{ "NationShort": "GR", "NationEnName": "Greece", "NationName": "希腊" },
{ "NationShort": "GD", "NationEnName": "Grenada", "NationName": "格林纳达" },
{ "NationShort": "GP", "NationEnName": "Guadeloupe", "NationName": "瓜德罗普岛" },
{ "NationShort": "GU", "NationEnName": "Guam", "NationName": "关岛" },
{ "NationShort": "GT", "NationEnName": "Guatemala", "NationName": "危地马拉" },
{ "NationShort": "GG", "NationEnName": "Guernsey", "NationName": "根西岛" },
{ "NationShort": "GW", "NationEnName": "Guinea-Bissau", "NationName": "几内亚比绍" },
{ "NationShort": "GN", "NationEnName": "Guinea", "NationName": "几内亚" },
{ "NationShort": "GY", "NationEnName": "Guyana", "NationName": "圭亚那" },
{ "NationShort": "HT", "NationEnName": "Haiti", "NationName": "海地" },
{ "NationShort": "HN", "NationEnName": "Honduras", "NationName": "洪都拉斯" },
{ "NationShort": "HU", "NationEnName": "Hungary", "NationName": "匈牙利" },
{ "NationShort": "IS", "NationEnName": "Iceland", "NationName": "冰岛" },
{ "NationShort": "IN", "NationEnName": "India", "NationName": "印度" },
{ "NationShort": "ID", "NationEnName": "Indonesia", "NationName": "印度尼西亚" },
{ "NationShort": "IR", "NationEnName": "Iran", "NationName": "伊朗" },
{ "NationShort": "IQ", "NationEnName": "Iraq", "NationName": "伊拉克" },
{ "NationShort": "IE", "NationEnName": "Ireland", "NationName": "爱尔兰" },
{ "NationShort": "IM", "NationEnName": "Isle of Man", "NationName": "马恩岛" },
{ "NationShort": "IL", "NationEnName": "Indonesia", "NationName": "以色列" },
{ "NationShort": "IT", "NationEnName": "Italy", "NationName": "意大利" },
{ "NationShort": "JM", "NationEnName": "Jamaica", "NationName": "牙买加" },
{ "NationShort": "JP", "NationEnName": "Japan", "NationName": "日本" },
{ "NationShort": "JE", "NationEnName": "Jersey", "NationName": "新泽西州" },
{ "NationShort": "JO", "NationEnName": "Jordan", "NationName": "约旦" },
{ "NationShort": "KE", "NationEnName": "Kenya", "NationName": "肯尼亚" },
{ "NationShort": "KI", "NationEnName": "Kiribati", "NationName": "基里巴斯" },
{ "NationShort": "KR", "NationEnName": "Korea (South)", "NationName": "韩国" },
{ "NationShort": "KD", "NationEnName": "Korea (North)", "NationName": "朝鲜" },
{ "NationShort": "KW", "NationEnName": "Kuwait", "NationName": "科威特" },
{ "NationShort": "KG", "NationEnName": "Kyrgyzstan", "NationName": "吉尔吉斯斯坦" },
{ "NationShort": "LO", "NationEnName": "Laos", "NationName": "老挝" },
{ "NationShort": "LV", "NationEnName": "Latvia", "NationName": "拉脱维亚" },
{ "NationShort": "LB", "NationEnName": "Lebanon", "NationName": "黎巴嫩" },
{ "NationShort": "LS", "NationEnName": "Lesotho", "NationName": "莱索托" },
{ "NationShort": "LR", "NationEnName": "Liberia", "NationName": "利比里亚" },
{ "NationShort": "LY", "NationEnName": "Libya", "NationName": "利比亚" },
{ "NationShort": "LI", "NationEnName": "Liechtenstein", "NationName": "列支敦士登" },
{ "NationShort": "LT", "NationEnName": "Lithuania", "NationName": "立陶宛" },
{ "NationShort": "LU", "NationEnName": "Luxembourg", "NationName": "卢森堡" },
{ "NationShort": "MO", "NationEnName": "Macau", "NationName": "澳门（中国）" },
{ "NationShort": "MK", "NationEnName": "Macedonia", "NationName": "马其顿" },
{ "NationShort": "MW", "NationEnName": "Malawi", "NationName": "马拉维" },
{ "NationShort": "MY", "NationEnName": "Malaysia", "NationName": "马来西亚" },
{ "NationShort": "MG", "NationEnName": "Madagascar", "NationName": "马达加斯加" },
{ "NationShort": "MV", "NationEnName": "Maldives", "NationName": "马尔代夫" },
{ "NationShort": "ML", "NationEnName": "Mali", "NationName": "马里" },
{ "NationShort": "MT", "NationEnName": "Malta", "NationName": "马耳他" },
{ "NationShort": "MH", "NationEnName": "Marshall Islands", "NationName": "马绍尔群岛" },
{ "NationShort": "MQ", "NationEnName": "Martinique", "NationName": "马提尼克岛" },
{ "NationShort": "MR", "NationEnName": "Mauritania", "NationName": "毛里塔尼亚" },
{ "NationShort": "MU", "NationEnName": "Mauritius", "NationName": "毛里求斯" },
{ "NationShort": "YT", "NationEnName": "Mayotte", "NationName": "马约特" },
{ "NationShort": "MX", "NationEnName": "Mexico", "NationName": "墨西哥" },
{ "NationShort": "MD", "NationEnName": "Moldova", "NationName": "摩尔多瓦" },
{ "NationShort": "MC", "NationEnName": "Monaco", "NationName": "摩纳哥" },
{ "NationShort": "MN", "NationEnName": "Mongolia", "NationName": "蒙古" },
{ "NationShort": "ME", "NationEnName": "Montenegro", "NationName": "黑山" },
{ "NationShort": "MS", "NationEnName": "Montserrat", "NationName": "蒙特塞拉特" },
{ "NationShort": "MA", "NationEnName": "Morocco", "NationName": "摩洛哥" },
{ "NationShort": "MZ", "NationEnName": "Mozambique", "NationName": "莫桑比克" },
{ "NationShort": "MM", "NationEnName": "Myanmar", "NationName": "缅甸" },
{ "NationShort": "NA", "NationEnName": "Namibia", "NationName": "纳米比亚" },
{ "NationShort": "NR", "NationEnName": "Nauru", "NationName": "瑙鲁" },
{ "NationShort": "NP", "NationEnName": "Nepal", "NationName": "尼泊尔" },
{ "NationShort": "NL", "NationEnName": "Netherlands", "NationName": "荷兰" },
{ "NationShort": "NC", "NationEnName": "New Caledonia", "NationName": "新喀里多尼亚" },
{ "NationShort": "NZ", "NationEnName": "New Zealand", "NationName": "新西兰" },
{ "NationShort": "NI", "NationEnName": "Nicaragua", "NationName": "尼加拉瓜" },
{ "NationShort": "NE", "NationEnName": "Niger", "NationName": "尼日尔" },
{ "NationShort": "NG", "NationEnName": "Nigeria", "NationName": "尼日利亚" },
{ "NationShort": "NU", "NationEnName": "Niue", "NationName": "纽埃" },
{ "NationShort": "NF", "NationEnName": "Norfolk Island", "NationName": "诺福克岛" },
{ "NationShort": "NO", "NationEnName": "Norway", "NationName": "挪威" },
{ "NationShort": "OM", "NationEnName": "Oman", "NationName": "阿曼" },
{ "NationShort": "PK", "NationEnName": "Pakistan", "NationName": "巴基斯坦" },
{ "NationShort": "PW", "NationEnName": "Palau", "NationName": "帕劳" },
{ "NationShort": "PS", "NationEnName": "Palestine", "NationName": "巴勒斯坦" },
{ "NationShort": "PA", "NationEnName": "Panama", "NationName": "巴拿马" },
{ "NationShort": "PG", "NationEnName": "Papua New Guinea", "NationName": "巴布亚新几内亚" },
{ "NationShort": "PY", "NationEnName": "Paraguay", "NationName": "巴拉圭" },
{ "NationShort": "PE", "NationEnName": "Peru", "NationName": "秘鲁" },
{ "NationShort": "PH", "NationEnName": "Philippines", "NationName": "菲律宾" },
{ "NationShort": "PN", "NationEnName": "Pitcairn Islands", "NationName": "皮特凯恩群岛" },
{ "NationShort": "PL", "NationEnName": "Poland", "NationName": "波兰" },
{ "NationShort": "PT", "NationEnName": "Portugal", "NationName": "葡萄牙" },
{ "NationShort": "PR", "NationEnName": "Puerto Rico", "NationName": "波多黎各" },
{ "NationShort": "QA", "NationEnName": "Qatar", "NationName": "卡塔尔" },
{ "NationShort": "RE", "NationEnName": "Reunion", "NationName": "留尼汪岛" },
{ "NationShort": "RO", "NationEnName": "Romania", "NationName": "罗马尼亚" },
{ "NationShort": "RW", "NationEnName": "Rwanda", "NationName": "卢旺达" },
{ "NationShort": "RU", "NationEnName": "Russian Federation", "NationName": "俄罗斯联邦" },
{ "NationShort": "SH", "NationEnName": "Saint Helena", "NationName": "圣赫勒拿" },
{ "NationShort": "KN", "NationEnName": "Saint Kitts-Nevis", "NationName": "圣基茨和尼维斯" },
{ "NationShort": "LC", "NationEnName": "Saint Lucia", "NationName": "圣卢西亚" },
{ "NationShort": "VG", "NationEnName": "Saint Vincent and the Grenadines", "NationName": "圣文森特和格林纳丁斯" },
{ "NationShort": "SV", "NationEnName": "El Salvador", "NationName": "萨尔瓦多" },
{ "NationShort": "WS", "NationEnName": "Samoa", "NationName": "萨摩亚" },
{ "NationShort": "SM", "NationEnName": "Palestine", "NationName": "圣马力诺" },
{ "NationShort": "ST", "NationEnName": "Sao Tome and Principe", "NationName": "圣多美和普林西比" },
{ "NationShort": "SA", "NationEnName": "Saudi Arabia", "NationName": "沙特阿拉伯" },
{ "NationShort": "SN", "NationEnName": "Senegal", "NationName": "塞内加尔" },
{ "NationShort": "SC", "NationEnName": "Seychelles", "NationName": "塞舌尔" },
{ "NationShort": "SL", "NationEnName": "Sierra Leone", "NationName": "塞拉利昂" },
{ "NationShort": "SG", "NationEnName": "Singapore", "NationName": "新加坡" },
{ "NationShort": "RS", "NationEnName": "Serbia", "NationName": "塞尔维亚" },
{ "NationShort": "SK", "NationEnName": "Slovakia", "NationName": "斯洛伐克" },
{ "NationShort": "SI", "NationEnName": "Slovenia", "NationName": "斯洛文尼亚" },
{ "NationShort": "SB", "NationEnName": "Solomon Islands", "NationName": "所罗门群岛" },
{ "NationShort": "SO", "NationEnName": "Somalia", "NationName": "索马里" },
{ "NationShort": "ZA", "NationEnName": "South Africa", "NationName": "南非" },
{ "NationShort": "ES", "NationEnName": "Spain", "NationName": "西班牙" },
{ "NationShort": "LK", "NationEnName": "Sri Lanka", "NationName": "斯里兰卡" },
{ "NationShort": "SD", "NationEnName": "Sudan", "NationName": "苏丹" },
{ "NationShort": "SR", "NationEnName": "Suriname", "NationName": "苏里南" },
{ "NationShort": "SZ", "NationEnName": "Swaziland", "NationName": "斯威士兰" },
{ "NationShort": "SE", "NationEnName": "Sweden", "NationName": "瑞典" },
{ "NationShort": "CH", "NationEnName": "Switzerland", "NationName": "瑞士" },
{ "NationShort": "SY", "NationEnName": "Syria", "NationName": "叙利亚" },
{ "NationShort": "TJ", "NationEnName": "Tajikistan", "NationName": "塔吉克斯坦" },
{ "NationShort": "TW", "NationEnName": "Taiwan", "NationName": "台湾 （中国）" },
{ "NationShort": "TH", "NationEnName": "Thailand", "NationName": "泰国" },
{ "NationShort": "TT", "NationEnName": "Trinidad and Tobago", "NationName": "特立尼达和多巴哥" },
{ "NationShort": "TL", "NationEnName": "Timor-Leste", "NationName": "东帝汶" },
{ "NationShort": "TG", "NationEnName": "Togo", "NationName": "多哥" },
{ "NationShort": "TK", "NationEnName": "Tokelau", "NationName": "托克劳" },
{ "NationShort": "TO", "NationEnName": "Tonga", "NationName": "汤加" },
{ "NationShort": "TN", "NationEnName": "Tunisia", "NationName": "突尼斯" },
{ "NationShort": "TR", "NationEnName": "Turkey", "NationName": "土耳其" },
{ "NationShort": "AE", "NationEnName": "United Arab Emirates", "NationName": "土库曼斯坦" },
{ "NationShort": "UK", "NationEnName": "United Kingdom", "NationName": "英国" },
{ "NationShort": "US", "NationEnName": "United States", "NationName": "美国" },
{ "NationShort": "UY", "NationEnName": "Uruguay", "NationName": "乌拉圭" },
{ "NationShort": "UZ", "NationEnName": "Uzbekistan", "NationName": "乌兹别克斯坦" },
{ "NationShort": "VN", "NationEnName": "Vanuatu", "NationName": "瓦努阿图" },
{ "NationShort": "TM", "NationEnName": "Vatican City", "NationName": "梵蒂冈" },
{ "NationShort": "VE", "NationEnName": "Venezuela", "NationName": "委内瑞拉" },
{ "NationShort": "VN", "NationEnName": "Vietnam", "NationName": "越南" },
{ "NationShort": "WF", "NationEnName": "Wallis and Futuna", "NationName": "瓦利斯群岛和富图纳群岛" },
{ "NationShort": "EH", "NationEnName": "Western Sahara", "NationName": "西撒哈拉" },
{ "NationShort": "YE", "NationEnName": "Yemen", "NationName": "也门" },
{ "NationShort": "VN", "NationEnName": "Yugoslavia", "NationName": "南斯拉夫" },
{ "NationShort": "ZM", "NationEnName": "Zambia", "NationName": "赞比亚" },
{ "NationShort": "ZW", "NationEnName": "Zimbabwe", "NationName": "津巴布韦" }
]